### ISSUE TITLE
Hartenjagen bug

### ISSUE THREAD

**Issue by Jisu101** [IrenvanderBeekPXL/TerminalGames#5]
In hartenjagen, each player starts with excactly the same cards, also after a few rounds.
 Can u pls solve this?

**Comment by IrenvanderBeekPXL** [comment]
I will fix this, but if you don't want to wait till the next release and have some python knowledge, you can mayby fix it yourself and do a pull request.

**Comment by IrenvanderBeekPXL** [comment]
Thanks for reporting the bug. The new release canidate will not have this bug.

Thanks for playing
